"""empty message

Revision ID: 95ddccdae669
Revises: b2042a5cd38c
Create Date: 2024-10-08 11:12:58.126437

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "95ddccdae669"
down_revision = "b2042a5cd38c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("venues", schema=None) as batch_op:
        batch_op.add_column(sa.Column("county", sa.String(length=120), nullable=True))
        batch_op.drop_column("state")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("venues", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "state", sa.VARCHAR(length=120), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column("county")

    # ### end Alembic commands ###
