"""empty message

Revision ID: cc6516012e79
Revises: 95ddccdae669
Create Date: 2024-10-08 11:54:28.479534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6516012e79'
down_revision = '95ddccdae669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('genres')
        batch_op.drop_column('county')

    # ### end Alembic commands ###
